global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:

rule_files:

scrape_configs:
  - job_name: "redis-stats"
    scrape_interval: 10s
    metrics_path: /metrics
    basic_auth:
      username: admin
      password: "pass"
    static_configs:
      - targets: ["172.28.10.52:9200"]
